# Programming Assignment 5
---
**Author:** Carson Brower  
**Version:** 1.0  
**Semester:** Spring 2024 

This *notebook* contains my solution(s) to **Programming Assignment 5**

### Problem 1 - Language Translator

In [16]:
translations = dict([
    ('couch', 'sofá'),
    ('chair', 'silla'),
    ('man', 'hombre'),
    ('woman', 'mujer'),
    ('bear', 'oso'),
    ('cat', 'gato'),
    ('dog', 'perro'),
    ('one', 'uno'),
    ('child', 'nino'),
    ('sun', 'sol'),
    ('moon', 'luna'),
    ('earth', 'tierra'),
    ('truth', 'verdad'),
    ('false', 'falso'),
    ('book', 'libro'),
    ('word', 'palabra'),
    ('hello', 'hola'),
    ('goodbye', 'adios'),
    ('food', 'viveres'),
    ('where', 'donde'),
    
])
def translate_word(word):
    translated_word = translations.get(word.lower())
    if translated_word:
        return translated_word.lower()
    else:
        return None
while True:
    word = input("Enter a word to translate from English to Spanish (enter Q to stop): ").strip().upper()
    if word == 'Q':
        break
    elif word in translations:
        translation = translate_word(word)
        print(f"The Spanish word for {word.lower()} is {translation}.")
    else:
        print(f"The Spanish word for {word.lower()} is not in this dictionary.")
    

Enter a word to translate from English to Spanish (enter Q to stop):  Q


### Problem 2 - Translating Morse Code

In [18]:

morse_code_mappings = {
    'A': '.-', 'B': '-...', 'C': '-.-.', 'D': '-..', 'E': '.', 'F': '..-.', 'G': '--.', 'H': '....', 'I': '..', 'J': '.---',
    'K': '-.-', 'L': '.-..', 'M': '--', 'N': '-.', 'O': '---', 'P': '.--.', 'Q': '--.-', 'R': '.-.', 'S': '...', 'T': '-',
    'U': '..-', 'V': '...-', 'W': '.--', 'X': '-..-', 'Y': '-.--', 'Z': '--..',
    '0': '-----', '1': '.----', '2': '..---', '3': '...--', '4': '....-', '5': '.....',
    '6': '-....', '7': '--...', '8': '---..', '9': '----.'
}
def translate_to_morse(sentence):
    morse_code = ''
    for char in sentence.upper():
        if char in morse_code_mappings:
            morse_code += morse_code_mappings[char] + ' '
        elif char == ' ':
            morse_code += '/ '
    return morse_code.strip()
while True:
    message = input("Enter a sentence to translate to Morse code (enter lowercase 'q' to quit): ")
    if message.lower() == 'q':
        print("stop")
        break
    morse_translation = translate_to_morse(message)
    print("Morse code translation:", morse_translation)

Enter a sentence to translate to Morse code (enter lowercase 'q' to quit):  Hello my name is Carson and my favorite number is 17


Morse code translation: .... . .-.. .-.. --- / -- -.-- / -. .- -- . / .. ... / -.-. .- .-. ... --- -. / .- -. -.. / -- -.-- / ..-. .- ...- --- .-. .. - . / -. ..- -- -... . .-. / .. ... / .---- --...


Enter a sentence to translate to Morse code (enter lowercase 'q' to quit):  q


stop


### Problem 3 - Comparing Minors/Majors

In [19]:

computer_science_minor = {'CS130', 'CS131', 'CS215', 'CS305', 'CS310', 'CS330', 'CS335', 'CS341', 'CS415'}
business_administration_minor = {'BUSA103', 'BUSA203', 'BUSA301','BUSA305', 'ACCT101', 'ECON110', 'FINA315', 'MATH125', 'MATH117'}
business_analytics_minor = {'BUSA103', 'BUSA245', 'BUSA346', 'CS150', 'DS160', 'DS300', 'MATH117', 'MATH125', 'MATH205'}
data_science_major = {'BUSA103', 'BUSA245', 'BUSA346', 'CS150', 'DS160', 'DS300', 'DS450', 'MATH205', 'MATH215', 'MATH430', 'ECON410', 'ECON322', 'ECON351', 'DS444',
'ECON110', 'ECON111', 'MATH117'}
overlap_courses = business_administration_minor.intersection(business_analytics_minor)
print("Courses overlapping between Business Administration and Business Analytics minors:", overlap_courses)
all_courses = business_administration_minor.union(computer_science_minor)
print("Courses required for Business Administration minor and Computer Science minor:", all_courses)
ba_only_courses = business_administration_minor.difference(business_analytics_minor)
print("Courses in Business Administration minor but not in Business Analytics minor:", ba_only_courses)
cs_ds_overlap = computer_science_minor.intersection(data_science_major)
if cs_ds_overlap:
    print("There are overlapping courses between Computer Science major and Data Science major.")
else:
    print("There are no overlapping courses between Computer Science major and Data Science major.")
ba_in_ds = business_analytics_minor.issubset(data_science_major)
if ba_in_ds:
    print("Business Analytics minor is completely subsumed by Data Science major.")
else:
    print("Business Analytics minor is not completely subsumed by Data Science major.")


Courses overlapping between Business Administration and Business Analytics minors: {'MATH125', 'BUSA103', 'MATH117'}
Courses required for Business Administration minor and Computer Science minor: {'CS330', 'CS130', 'MATH117', 'CS305', 'ACCT101', 'BUSA301', 'BUSA203', 'CS215', 'CS131', 'CS341', 'ECON110', 'FINA315', 'CS415', 'CS335', 'BUSA103', 'CS310', 'MATH125', 'BUSA305'}
Courses in Business Administration minor but not in Business Analytics minor: {'ACCT101', 'BUSA301', 'BUSA203', 'ECON110', 'FINA315', 'BUSA305'}
There are no overlapping courses between Computer Science major and Data Science major.
Business Analytics minor is not completely subsumed by Data Science major.


### Problem 4 - Working with NumPy

In [17]:
import numpy as np
array1 = np.random.randint(0, 21, size=(5, 5))
array2 = np.random.randint(0, 21, size=(5, 5))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)
matrix_product = np.matmul(array1, array2)
dot_product = np.dot(array1.flatten(), array2.flatten())
determinant_array1 = np.linalg.det(array1)
inverse_array1 = np.linalg.inv(array1)
determinant_array2 = np.linalg.det(array2)
inverse_array2 = np.linalg.inv(array2)
array1d_1 = np.linspace(0, 1, num=20)
array1d_2 = np.linspace(1, 2, num=20)
combined_array = np.concatenate((array1d_1, array1d_2))
reshaped_array = combined_array.reshape(10, 4)
print("Matrix Product:")
print(matrix_product)
print("Dot Product:")
print(dot_product)
print("Determinant of Array 1:", determinant_array1)
print("Inverse of Array 1:")
print(inverse_array1)
print("Determinant of Array 2:", determinant_array2)
print("Inverse of Array 2:")
print(inverse_array2)
print("Combined 1D array:")
print(combined_array)
print("Reshaped 2D array:")
print(reshaped_array)

Array 1:
[[ 3  5 17  6  4]
 [10  0  7 13  5]
 [20 19  3  2 16]
 [18 15 14  5  2]
 [18 19 19  1  6]]
Array 2:
[[13 17 10 13 15]
 [ 4  5  6 19 14]
 [13 17  2  2 16]
 [ 0 15  3 16  3]
 [ 5  1  9  5 17]]
Matrix Product:
[[300 459 148 284 473]
 [246 489 198 377 386]
 [455 532 470 739 892]
 [486 696 331 637 753]
 [587 745 389 679 945]]
Dot Product:
2420
Determinant of Array 1: -133434.9999999999
Inverse of Array 1:
[[-0.19151647  0.14344063 -0.0705587  -0.16517405  0.25135834]
 [ 0.19563083 -0.19754937  0.10365346  0.30626897 -0.34429498]
 [-0.01972496  0.04811331 -0.04937235 -0.10994866  0.14136471]
 [ 0.16156181 -0.08101323  0.07004909  0.25086372 -0.31061566]
 [-0.00941282  0.0563945   0.02811107 -0.16796942  0.10697343]]
Determinant of Array 2: 269819.99999999977
Inverse of Array 2:
[[ 0.11162256  0.06798236 -0.00806834 -0.13178045 -0.12362686]
 [-0.01726336 -0.06357201  0.02515381  0.076892    0.03034245]
 [ 0.09410718 -0.10235713 -0.09568601  0.03017567  0.08599066]
 [ 0.01465421  0.07